---
deployment:
  tasks:
    - export DEPLOYPATH=/home/YOUR_CPANEL_USERNAME/public_html/
    - /bin/mkdir -p $DEPLOYPATH
    - /usr/bin/find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.cpanel.yml' -exec /bin/cp -R {} $DEPLOYPATH \;
